site_name: BioDynaMo User Documentation
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite
pages:
    - Home: index.md
    - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
    - Tutorials:
      - Hello World: hello_world.md
      - Visualization: visualization.md
      - Diffusion: diffusion.md
      - Tumor Concept: jean_tuto.md
      # - Soma Clustering: soma_clustering.md
    - Documentation:
      - Substance Initialization: substance_initializers.md
      - GPU Acceleration: gpu_acceleration.md
    - Contact: contact.md
