language: c++

matrix:
  include:
    # Default build on osx
    - os: osx
      compiler: clang
      env: SCRIPT=./travis.sh
    # Default build on linux
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT=./travis.sh
    # Test development installation on linux
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      env: SCRIPT="script/dev/test_ubuntu_16.04_install_script/host.sh $TRAVIS_BRANCH"

script:
  - $SCRIPT

services:
  - docker

notifications:
  slack: cernopenlab:2MzX9lwS6W9nU47MuY1qSmk9

after_failure:
  - "cat /Users/travis/build/BioDynaMo/biodynamo/build/*.log"
