language: c++

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      group: edge

script:
  - ./travis.sh

services:
  - docker

notifications:
  slack: cernopenlab:2MzX9lwS6W9nU47MuY1qSmk9
