name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install libomp tbb open-mpi git pyenv llvm wget cmake ninja p7zip
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.9

    - name: Build BioDynaMo
      shell: bash
      run: |
        cmake -G Ninja -Dopencl=ON -Dparaview=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ \
          -DCMAKE_CXX_FLAGS="-isysroot `xcrun --show-sdk-path`" \
          -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
          -DCMAKE_EXE_LINKER_FLAGS_INIT=-L/usr/local/opt/llvm/lib \
          -DCMAKE_SHARED_LINKER_FLAGS_INIT=-L/usr/local/opt/llvm/lib \
          -B build
        cmake --build build --parallel --config Release

    - name: Test BioDynaMo
      shell: bash
      run: |
        . bin/thisbdm.sh
        bin/biodynamo-unit-tests
      working-directory: build

    - name: Create BioDynaMo archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/biodynamo-mac.zip ./build

    # Upload BioDynaMo binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: biodynamo-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/biodynamo-mac.zip
        asset_name: biodynamo-mac.zip
        asset_content_type: application/zip
